### PR TITLE
add cluster 0.3.1

### PR DESCRIPTION
**Pull request by hsanjuan**

### CODE REVIEW

**Comment by hsanjuan** [comment]
```
[15:07:13] ~/i/distributions (cluster-0.3.1|✚4) $ 
ipfs object diff /ipns/dist.ipfs.io (tail -n1 versions )
~ QmRQ6GigoWzrgYemAE7c5AEiSjJKMLGPtoXS3Ao9hmZJdY QmTe7oG1F5UWwgKFjWMT31EX4bYdQVRAXjR3rxZjGWGonW "gx/versions"
~ QmZnTu6TrfK19TPohvAcvRKsbEMXUyEojvNwLictii729U QmWttQVsm5Wt19UoBaV9J5er9zc1X6BrSwHQB9VNZcZStJ "gx-go/versions"
~ QmTdL2atcuz5cSCCfhbeJyraHPSKijwXwzGkvb2D8VstXj QmS1i3NuMAGSquXDHeAYUDpEAkE5YN6hg8Vv4H8YzvR1ba "index.html"
~ QmWw5cTky9MhoVDwpnJZNz6tnnZjLcBkdDixfzZj63v5UT QmUykHAi1aSjMzHw3KmBoJjqRUQYNkFXm8K1y7ZsJxpfPH "index.xml"
~ QmVgRHzZYu8BTwHfArNdaWVW8goTGUTA2VTcNRm9bcHqM2 Qmc77H4BQQGXNydt1KeWNPMepQhU1e4atTaV6xJMVx7Zdu "ipfs-cluster-ctl/versions"
+ QmUmG3Yj17V3ePwg2nz3DU5d41Rh4VqAdjSbHPrLsG16bU "ipfs-cluster-ctl/v0.3.1"
~ QmeDsG7BJR8oiWgW5i7fpQPHsjpKKMQay4tMkeVqu6qi4X QmZHjhL5q8qsXdYfpgN9xJAPFNCKtDjjnSEDEVUKRkY1HF "ipfs-cluster-service/versions"
+ QmXzTFecrpx52VYyDxMYDyXg31K28STzwASuoLmjrrBeCo "ipfs-cluster-service/v0.3.1"
~ QmaLNgbd3cxVikdECL7GhyuTSr5oVWAeZCcmjJkiDYntFn QmVkRNRVrzs9NsUViE1SGpHpimPAtt1aa3ASJiMv34NMtz "ipget/versions"
~ QmPgnfFXi1DqWX1DuSCCPGempbvWAt8YPq6KL4Rufmmf7G QmY4uSCABEdFNSVNt2ungtH2ZCuvyyxVpjbaN8k9KkDFie "sitemap.xml"
+ QmZGGPk41zv69RqFddB98kXojoctQD8LFgoLanCigvpWpF "ipfs-pack"
```

It seems someone has made changes that are not commited in any fashion (gx at least). Since this is the third time in a row that I find this issue, and it doesn't follow the release protocol, I will override those changes.

**Comment by hsanjuan** [comment]
NEw hash is QmdreKPMAndVpJxJJUSHt6CJGGaqkeMWkNVCutkVq11yk1

**Comment by whyrusleeping** [comment]
Did we somehow rebuild all of ipfs-pack?

**Comment by whyrusleeping** [comment]
Also, the versions file youre referencing is not committed, I cant replicate the above

**Comment by hsanjuan** [comment]
`ipfs object diff /ipns/dist.ipfs.io QmdreKPMAndVpJxJJUSHt6CJGGaqkeMWkNVCutkVq11yk1`

**Comment by hsanjuan** [comment]
good question with pack, I run my builds after `make clean`, so I should have got whatever was published

**Pull request merged**
