### PR TITLE
chore: release ipget v0.8.1

### PR DESCRIPTION
**Pull request by galargh**
This release is needed to address https://github.com/ipfs/ipget/issues/100 (cc @vmx).

Since the last ipget release (https://github.com/ipfs/distributions/pull/342), the release process was dockerised (https://github.com/ipfs/distributions/pull/352) and the binaries are now produced on `ubuntu:20.04` (https://github.com/ipfs/distributions/blob/master/Dockerfile#L1).

I have also verified that the new `ipget` release will work on `ubuntu:20.04` by downloading and starting a nightly release of `ipget` (https://bafybeihtrnldjkbilpztkuqvinawsykbu2gf4u7fvdmfib663epuaudmkq.ipfs.dweb.link/ipget/nightly-2022-04-14) inside a `ubuntu:20.04` container.

### CODE REVIEW

**Comment by vmx** [comment]
Thanks! I can confirm that it works on Ubuntu 20.04.

It might make sense to merge https://github.com/ipfs/ipget/pull/107 before a new release is published.

**Comment by lidel** [comment]
@galargh we need 0.8.1 that has fixed --version :pray:

**Comment by galargh** [comment]
> @galargh we need 0.8.1 that has fixed --version 🙏 (i.e. https://github.com/ipfs/ipget/blob/5397b0666d7e90d78c1566ecb90f289dad9d9ec1/main.go#L35)

Got it! Updated the PR to 0.8.1.

**Review by lidel — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
