### PR TITLE
Improve on the UI

### PR DESCRIPTION
**Pull request by Dignifiedquire**
Start resolving the issues from #24 

- [x] Bit fat download button with os detection
- [x] Increase hight
- [ ] Add underlines to links
- [ ] Fix mobile version issues

Current preview

screen shot 2016-01-14 at 22 06 33

@jbenet please take a look

@whyrusleeping 0.3.11 is not setup for being built yet could you add that please?

### CODE REVIEW

**Comment by jbenet** [comment]
Button + height LGTM!

**Comment by jbenet** [comment]
(button looks great actually)

**Comment by jbenet** [comment]
just thought: should we add OS icons from font-awesome wherever relevant? (say, to left of the text in the grid, and to the auto-detect button?)

**Comment by jbenet** [comment]
could we use a down-arrow on the button? common symbols help catch attention.

**Comment by Dignifiedquire** [comment]
> could we use a down-arrow on the button? common symbols help catch attention.

I'd rather not add an icon to the download button, as I already needed to make the font quite small as some of those names are very long (I'm looking at you `fs-repo-migrations`) and there is simply not enough space on some screen sizes to add it

**Comment by Dignifiedquire** [comment]
> just thought: should we add OS icons from font-awesome wherever relevant? (say, to left of the text in the grid, and to the auto-detect button?)

I think it's not needed on the download button, will think about adding it to the grid, but I haven't yet found a high quality free bsd icon that works in small sizes to use, so I'd rather not add them if we don't have good ones for all platforms.

> (button looks great actually)

Thanks :)

**Comment by RichardLitt** [comment]
Code LGTM

**Comment by jbenet** [comment]
@Dignifiedquire 
- what about just the icon instead of repeating the name? or just the icon when the screen width is below some threshold  (`@media` queries, woo)?
- arrows matter, so does green. Green + down arrow are both action buttons across tons of sites and people's minds are well conditioned. (i once ran an a/b test with green button vs gray button and green was ~5x more likely to be clicked.) i know it fits less with the blue, _any_ shred of confusion finding the button is worse than a feeling the colors don't entirely fit.

**Comment by jbenet** [comment]
- we should add the icons at some point, but i'm ok delaying it for a future PR. 
- "speed of finding download link and clicking it" is way more important than "the icons look a bit bad" here. 
- freebsd: https://openclipart.org/image/2400px/svg_to_png/226471/1441081059.png
- maybe the puffer to the right for openbsd?

**Comment by Dignifiedquire** [comment]
> arrows matter, so does green. Green + down arrow are both action buttons across tons of sites and people's minds are well conditioned. (i once ran an a/b test with green button vs gray button and green was ~5x more likely to be clicked.) i know it fits less with the blue, any shred of confusion finding the button is worse than a feeling the colors don't entirely fit.

Okay two things

* Down arrow. I'm not sure why you think this is so important, I know it was used for some time but these days I have a hard time to find any large download page that still uses an arrow for the download button. (See below for some examples of popular download pages that just manage fine without icons)
* Green vs Grey. The reason for your a/b test to go to green is clear, but not because of green, but rather because it was colored (green) vs uncolored (gray) so I see no conclusion from that to use a green button here in a design that was not at all intended to use green. If you want a different highlight color we *could* use orange, as it actually fits and contrasts nicely to blue, but I'm not sure that kind of highlight is needed

### Examples

#### Chrome
screen shot 2016-01-15 at 10 03 41

#### Adobe
screen shot 2016-01-15 at 10 03 51

#### Go-lang
screen shot 2016-01-15 at 10 04 46

**Comment by Dignifiedquire** [comment]
> "speed of finding download link and clicking it" is way more important than "the icons look a bit bad" here.

Speed of finding the link is important I totally agree, but if the icons are not actually distinguishable and look bad they actually have the opposite effect as people are then spending their time trying to figure out what the icon is supposed to mean.

**Comment by Dignifiedquire** [comment]
New version

**Pull request merged**
