### PR TITLE
fix(build): Target name for go-ipfs is go-ipfs.zip

### LINKED ISSUE #29: release files for go-ipfs should be go-ipfs.zip not ipfs.zip

### PR DESCRIPTION
**Pull request by Dignifiedquire**
Closes #29

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@Dignifiedquire your indenting is wrong. Also, you tested this, right?

**Comment by Dignifiedquire** [comment]
Fixed indentation, and yes I tested it

**Comment by Dignifiedquire** [comment]
https://ipfs.io/ipfs/QmT6pAkgEyfWfAvrg7kQcN6yaMoHQ8Co9WonKiCqzAjsgZ/

**Comment by Dignifiedquire** [comment]
Shiped on http://dist.ipfs.io/

**Pull request merged**
