### PR TITLE
Added ipfs-cluster v0.1.0

### PR DESCRIPTION
**Pull request by hsanjuan**
Example: https://ipfs.io/ipfs/QmSSU7RjjDZrRQh12DnBnPkjzYujJ8EdSVXjD3cSxBJLSx

@lgierth is rolling this something you can help with ?

### CODE REVIEW

**Comment by hsanjuan** [comment]
diff:

```
~ QmWJJVfWC6enEWx246YbrfuW1VDusCsaWnwFy4h6A1JD36 QmQ4LLzRxzz3Po16fSTfpfveqokzGEbfz1kgPsKwebRsS2 "go-ipfs/versions"
+ QmbGVQNZ6YgHyFnF4oariJt2QcxYGGiSNhW5VL1uuxkRb9 "go-ipfs/v0.4.10-rc1"
~ QmTe7oG1F5UWwgKFjWMT31EX4bYdQVRAXjR3rxZjGWGonW QmNbvhXdFahnWJCfTzUR1Zc6ejFB3iLBLCP1S7yWapTMxs "gx/versions"
~ QmWttQVsm5Wt19UoBaV9J5er9zc1X6BrSwHQB9VNZcZStJ QmeGGMNf2dU2UfAiJuSH1hhYjGk5Tig4S2idrT1Fq4L2B9 "gx-go/versions"
~ QmWqDVoVgkGfxjdLdKRFpaP8XiDDswWgzoVqVwYQyDncoy QmUq66L3ma7XNHi8ZpaMdWn7U55Z8qgnYc9fESYjm2jyDX "index.html"
~ QmU4seo647CksUrwAGwcHWim1gpK3kPf8rYV1NDFMNgkRs QmPvoWzkXPXJEUbEksyrc85UYQiPSbdkS3NQ8BSbdL4kxw "ipfs-cluster-ctl/versions"
+ QmTHGsvDygfwdCfeC11ouUSTMYt32S9K7GRh4UY1NcXjQL "ipfs-cluster-ctl/v0.1.0"
~ QmU4seo647CksUrwAGwcHWim1gpK3kPf8rYV1NDFMNgkRs QmPvoWzkXPXJEUbEksyrc85UYQiPSbdkS3NQ8BSbdL4kxw "ipfs-cluster-service/versions"
+ QmVtGGATRHDPPp7E7K94WM9FXM7NYxcUzGTNNuGzweN7Tp "ipfs-cluster-service/v0.1.0"
~ QmY4uSCABEdFNSVNt2ungtH2ZCuvyyxVpjbaN8k9KkDFie Qmd8GtqxfpyeznmALi7qTbc9rhorpYSHAGSkLqrzYc7PQQ "sitemap.xml"
```

**Comment by whyrusleeping** [comment]
@hsanjuan sorry about that, just pushed a previously unpushed commit

**Comment by hsanjuan** [comment]
Rebased to master, rebuilt and new hash looks much better:

https://ipfs.io/ipfs/QmRQ7KB6wCoMbj6D4E38SAAD6NoE7XRkCS7vqRe3YJFZRo

**Comment by hsanjuan** [comment]
published

**Pull request merged**
