### PR TITLE
fix: update nightly status on commits

### PR DESCRIPTION
**Pull request by lidel**
Problem – https://github.com/ipfs/distributions/issues/531 got fixed, but the "Problem with" message on commit remains: 

>

### CODE REVIEW

**Review by galargh — APPROVED** [review]

**Comment by galargh** [comment]
There's definitely a way to update the check instead of creating a new one: https://docs.github.com/en/rest/reference/checks#update-a-check-run

If you think that'd be worth the work here, let me know - I can look into it.

**Comment by lidel** [comment]
@galargh yeah, I think if we can update then it's worth keeping the status – this is low priority – feel free to take over this PR when you have time.

**Comment by lidel** [comment]
Let's merge this for now, to avoid false-negatives in https://github.com/ipfs/distributions/commits/master

**Comment by galargh** [comment]
> @galargh yeah, I think if we can update then it's worth keeping the status – this is low priority – feel free to take over this PR when you have time.

Sorry, I missed this message. I created an issue so that I remember to come back to this - https://github.com/protocol/w3dt-stewards/issues/31

**Pull request merged**
