### PR TITLE
Set container timezone to UTC

### PR DESCRIPTION
**Pull request by gammazero**

### CODE REVIEW

**Review by marten-seemann — COMMENTED** [review]
Why LA, why not UTC?

**Comment by gammazero** [comment]
@marten-seemann PL has headquarters in pacific time, but really that can be anything.  If we are always going to use UTC, which should be the container default, do we really need this PR?

**Comment by marten-seemann** [comment]
> If we are always going to use UTC, which should be the container default, do we really need this PR?

I'm not sure which is issue is fixed by this PR, you tell me ;)

While it may be true that PL is headquartered in Pacific Time, it very much understands itself as an international (interplanetary?) company. The default timezone, when no other is applicable, is UTC, which is why I suggested it.

**Comment by aschmahmann** [comment]
> If we are always going to use UTC, which should be the container default, do we really need this PR?

We should run some tests to see if/how the new docker containers fix our problems. We've only done one release using the containers and it's on my machine. If you try doing a local build of the website and diff with dist.ipfs.io and you don't see lots of changes in the XML file of the RSS feed #330 then we're already good to go. Otherwise, something's not going quite right.

**Review by lidel — APPROVED** [review]
Given that we merged #369 and #367 and we default to UTC all over the place now, 
I rebased this PR to switch to use  UTC in Docker as well.

**Pull request merged**
